baseURL = "https://aauk.org"
languageCode = "en-gb"
title = "Activity Alchemist"
paginate = 10
theme = "PaperMod" 

enableRobotsTXT = true
buildDrafts = false
buildFuture = true
buildExpired = false
publishDir = "docs"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Activity Alchemist"
description = "Activity Alchemist"
keywords = [ "Activity Alchemist" ]
author = "Activity Alchemist"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "Mon 2 January, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = false
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Activity Alchemists"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "ExampleSite"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Activity Alchemists"
  Content = "Hello!"

  [[params.socialIcons]]
  name = "twitter"
  url = "#"

  [[params.socialIcons]]
  name = "instagram"
  url = "#"

  [[params.socialIcons]]
  name = "facebook"
  url = "#"

#[params.analytics.google]
#SiteVerificationTag = "XYZabc"

#[params.analytics.bing]
#SiteVerificationTag = "XYZabc"

#[params.analytics.yandex]
#SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "Activities"
name = "activities"
url = "/activities/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "About us"
name = "about"
url = "/about/"
weight = 30

[markup.highlight]
noClasses = false
